### ISSUE TITLE
Framework Compatibility

### ISSUE THREAD

**Issue by jolux** [Tarrasch/antigen-hs#15]
Since antigen-hs does not have the framework that oh-my-zsh does, (it being just a plugin manager) perhaps you could provide a guide for porting themes and/or plugins for full compatibility with OMZless installations?

**Comment by Tarrasch** [comment]
Thanks for reminding me about the license @jolux , have you found any work around for the issue you have here?

By the way, isn't this solved by just setting `setopt prompt_subst`? Though this is not easy to tell where it should go? Should the plugin loader set that or should the plugin itself set it? I mean, what if two plugins have conflicting requirements on the environment?

**Comment by jolux** [comment]
I think the issue is more that I do not have the git plugin included with OMZ installed. Perhaps you should make it clear that themes sometimes require plugins that antigen-hs does not include by default.

I’ve since decided having git status in my prompt is unnecessary though.

Is there a way to allow antigen-hs to install plugins directly from OMZ’s plugins and themes directory, perhaps using regex? This feature would be very useful.

If not, you can close this issue.

**Comment by Tarrasch** [comment]
From the README (added after this issue was opened :)):

```haskell
  -- If you use a plugin that has sub-plugins. You can specify that as well
  --
  -- NOTE: If you want to use oh-my-zsh for real (please don't), you still need
  -- to set the $ZSH env var manually.
  , (bundle "robbyrussell/oh-my-zsh")
     { sourcingLocations = [ "plugins/wd"
                           , "plugins/colorize"] }
```

So then it will install the plugins `wd` and `colorize`.

I wouldn't generalize it to that "themes sometimes require plugins that antigen-hs does not include by default". It's just that a individual plugins (powerline-theme) when bundled (in omz) might rely on something like a `common.zsh` for the bundle, and then it's not enough to only source the files of the plugin.

But maybe you're actually right on this (it's a plugin-depedency, not `common.zsh`-depedency). Can you try using the code sample I pasted above and adjust it to use the two plugins (git-plugin and powerline-theme) and see if it works?

**Comment by jolux** [comment]
Sorry to lag behind on this. Antigen-hs configuration was inhibiting my use of zsh so I switched back to the dark side of omz.

Apologies. I'll gladly work on the plugin dependency issues with you if you'd like, I have some ideas.
