### ISSUE TITLE
Handle completions / compdefs via single file

### ISSUE THREAD

**Issue by blueyed** [Tarrasch/antigen-hs#17]
I've just created https://github.com/zsh-users/antigen/pull/110 for antigen, to make it properly handle a file location, which is a `#compdef`.

As far as I can see, antigen-hs does not handle this as well.

I guess the existing default sourcing strategy could be made smarter to recognize files starting with `#compdef`, too?

**Comment by Tarrasch** [comment]
Hmm, I think I know what it should do solely based on your code in zsh-users/antigen#110 (thanks for referring to it!). I'm happy to implement this if you want to stay away from Haskell. :)

Do you have any "test case" though? I mean, a sample plugin that antigen-hs should be able to handle.

**Comment by blueyed** [comment]
> I'm happy to implement this if you want to stay away from Haskell. :)

:+1: :)

I've initially tried it with a PR for "hub":

> antigen bundle blueyed/hub --loc=etc/hub.zsh_completion --branch=improve-zsh-completion

This would be problematic, because the file should be named `_hub`, but creating a symlink might be too much there.

This however should work:

> antigen bundle blueyed/hub --loc=etc/_hub --branch=improve-zsh-completion

**Comment by Tarrasch** [comment]
Hi @blueyed. I started to implement this, but I'm feeling a bit worried about how you implemented this in zsh-users/antigen#110. Doesn't your patch in [1] make it *either* `source` or `fpath+=`? Is that desired? I ask because in other code branches you do both. I think an implementation in antigen-hs could be more elegant by it's keyword-style parameters. I imagine a syntax like:

```haskell
bundle "blueyed/hub" {
    fpathLocation = "etc/_hub"
  }
```

The way you do the conditional in zsh-users/antigen#110 seems hacky to me, you kind of dispatch on `$2` to see if it meant as a source-location or a fpath-location. I think it makes more sense for it configured explicitly by the user of antigen.

Does any of this make sense?

[1]: https://github.com/zsh-users/antigen/pull/110/files#diff-62b3679d24a34998b79c2da4ab6620a9

**Comment by blueyed** [comment]
> Doesn't your patch in 1 make it either source or fpath+=? Is that desired?

Yes. compdefs should not get sourced.

> fpathLocation = "etc/_hub"

That should be just "etc/" then.  The file's dir should be added to the $fpath, not the file itself.

**Comment by Tarrasch** [comment]
So 

```hs
bundle "blueyed/hub" {
    fpathDirectory = "etc"
  }
```

then. Would only being able to specify one directory cover most use cases you think? Or should I make it a bit more generic?

**Comment by Tarrasch** [comment]
Would only specifying the directory make it work for both

    antigen bundle blueyed/hub --loc=etc/hub.zsh_completion --branch=improve-zsh-completion
 
and

    antigen bundle blueyed/hub --loc=etc/_hub --branch=improve-zsh-completion

btw?

**Comment by blueyed** [comment]
> Would only specifying the directory make it work for both

Hmm, do you mean with or without my PR?

For a completion / compdef, you want its dir in $fpath.  _And_ the file needs to have a special name (starting with an underscore).
Therefore a repo where the file has not a proper name, like with `hub/hub`, is more problematic to install, because you need to create an additional symlink ( - which could be done through antigen-hs).

**Comment by Tarrasch** [comment]
Finally sent the PR for this (referenced), can you take a look @blueyed ? :)
